# SPDX-License-Identifier: GPL-2.0
# Nexell Platform Support

obj-$(CONFIG_VIDEO_NEXELL_CODEC) += nx_vpu.o

nx_vpu-objs += nx_vpu_v4l2.o
nx_vpu-objs += nx_vpu_dec_v4l2.o
nx_vpu-objs += nx_vpu_enc_v4l2.o
nx_vpu-objs += nx_port_func.o
nx_vpu-objs += nx_vpu_api.o
nx_vpu-objs += nx_vpu_encoder.o
nx_vpu-objs += nx_vpu_decoder.o
nx_vpu-objs += nx_jpu_api.o
nx_vpu-objs += vpu_hw_interface.o
nx_vpu-objs += nx_vpu_gdi.o
