# SPDX-License-Identifier: GPL-2.0
#
# Nexell Clock specific Makefile
#

obj-$(CONFIG_COMMON_CLK_NEXELL) += clk-nexell-pll.o clk-nexell.o clk-nexell-fixed-factor.o
obj-$(CONFIG_COMMON_CLK_NXP3220) += clk-nxp3220.o
obj-$(CONFIG_COMMON_CLK_NXP3220) += clk-nxp3220-cmu.o
obj-$(CONFIG_COMMON_CLK_NXP3220) += clk-nxp3220-cpu.o
obj-$(CONFIG_COMMON_CLK_NXP3220) += clk-nxp3220-ddr.o
obj-$(CONFIG_COMMON_CLK_NXP3220) += clk-nxp3220-usb.o
obj-$(CONFIG_COMMON_CLK_NXP3220) += clk-nxp3220-mm.o
