# SPDX-License-Identifier: GPL-2.0
# Nexell Platform Support

obj-$(CONFIG_SND_NEXELL_PCM)	+= nexell-snd-pcm.o
obj-$(CONFIG_SND_NEXELL_I2S)	+= nexell-snd-i2s.o
obj-$(CONFIG_SND_NEXELL_PDM)		+= nexell-snd-pdm.o
obj-$(CONFIG_SND_NEXELL_NULL_CODEC)	+= nexell-snd-null-codec.o

nexell-snd-pcm-objs		:= nexell-pcm.o
nexell-snd-i2s-objs		:= nexell-i2s.o
nexell-snd-pdm-objs			:= nexell-pdm.o nexell-pdm-card.o
nexell-snd-null-codec-objs		:= nexell-null-codec.o
